### ISSUE TITLE
Secret key & Debug

### ISSUE THREAD

**Issue by jicjjang** [sujinleeme/official-website#1]
settings에서 Secret key는 숨겨주셔야 될 것 같아요
Debug로 False를 ㅠㅠ....
uri들이 그대로 노출되네요...

/simple-4-step-approach-build-better-portfolio 페이지 보고싶어요!

**Comment by sujinleeme** [comment]
안녕하세요. 리포팅 해주셔서 진심으로 감사드립니다.
해당 내용 수정 반영 하였습니다. 번역 글은 [브런치](https://brunch.co.kr/@sujinleeme/2)에서 확인하실 수 있습니다. 감사합니다.
